### ISSUE TITLE
docker.pull keeps JVM alive for a long time

### ISSUE THREAD

**Issue by RichoDemus** [spotify/docker-client#405]
## Description

After having run docker.pull() and docker.close, a thread called jersey-client-async-executor-0 is left alive for quite some time, preventing the JVM from terminating
## How to reproduce

I have created a small repo to reproduce this: https://github.com/RichoDemus/docker-pull-bug  
but I'm basically just doing

```
final DockerClient docker = DefaultDockerClient.fromEnv().build();  
docker.pull("alpine:latest");  
docker.close();  
```
## What do you expect

I expect that after doing docker.close and exiting the main method, the program should terminate right away
## What happened instead

The process stays alive for about a minute extra
## Software:
- docker version: 1.10.3
- docker-client version: 3.6.6
## Full backtrace

N/A

**Comment by johnflavin** [comment]
This could be related to a Jersey issue ([2878](https://java.net/jira/browse/JERSEY-2878)). Jersey was keeping connections with an `InputStream` alive after their `close()` methods were called. It was reportedly fixed in version 2.21; `docker-client` uses 2.19.

But I don’t know enough about what is going on in the `pull()` method to know if this Jersey issue applies. Nor do I know what JUnit is doing differently to quickly close the connection during the test. :confused:

**Comment by plamentotev** [comment]
I get this behavior will all commands not only pull. For example with the following code:
```java
        try(DockerClient dockerClient = DefaultDockerClient.builder()
                .uri("http://localhost:2375/")
                .build()) {
            System.out.println(dockerClient.version());
        }
``` 
the program hangs for about a minute after the version is printed to the console. Of course the reason is the connection pool used  by jersey. It uses non-daemon threads so this keeps the application alive. Still not sure why there are alive threads in the pool after the `dockerClient` is closed.

I've updated the jersey version to 2.21 and I don't see any difference too.

**Comment by plamentotev** [comment]
I found it. The offender is [JERSEY-2969 - Client#close() not shutting down Async Executor](https://java.net/jira/browse/JERSEY-2969). it's fixed in 2.22.2. updating jersey dependency to 2.22.2 solved the problem.

**Comment by nfleury** [comment]
@plamentotev  I was facing the same issue. Switching jersey-client to 2.22.2 fixed the issue. Would be nice to update this lib version ?

**Comment by tobiaskohlbau** [comment]
Today I ran into the same issue. Are there any plans on updating jersey-client to 2.22.2 in the mainline version?
Would be glad if I maven version fixes this issue.

**Comment by davidxia** [comment]
@RichoDemus @plamentotev @johnflavin Thanks for the detailed investigation and work!

**Comment by davidxia** [comment]
#558 should fix this.
